THEME_DIR := "$(realpath ../aneotheme)"
FONTS_DIR := THEME_DIR + "/fonts"

PDFLATEX_FLAGS := "-shell-escape -interaction=nonstopmode -synctex=1"

default:
  @echo "usage: just compile <tex file>"

compile tex_file:
    #!/bin/bash
    export OSFONTDIR="{{FONTS_DIR}}//:$OSFONTDIR"
    export TEXINPUTS="{{THEME_DIR}}//:$TEXINPUTS"
    if which latexmk > /dev/null 2>&1; then
        echo "Using latexmk to compile the document."
        latexmk -lualatex $PDFLATEX_FLAGS "$(realpath {{tex_file}})"
    else
        echo "Using lualatex to compile the document."
        lualatex $PDFLATEX_FLAGS  "$(realpath {{tex_file}})"
    fi

clean:
   @rm -f *.aux *.log *.out *.toc *.nav *.snm *.pdf *.fdb_latexmk *.fls
